tf_eager_mode: False
model_summaries: False
neptune_project_name: 'rschiewer/predictor'

env_setting: 'gridworld_large_room' #'gridworld_3_rooms' #'gridworld_doors_teleporters' #'gridworld_3_rooms'
env_n_samples_per_env: 80000
env_mix_memory_fraction: 1.0
env_sample_mem_path_stub: 'samples/raw/'
env_mix_mem_path_stub: 'samples/mix/'
env_name_concat: '_and_'