ctrl_n_runs: 20
ctrl_n_plan_steps: 30
ctrl_n_warmup_steps: 3
ctrl_n_rollouts: 500
ctrl_n_iterations: 5
ctrl_top_perc: 0.2
ctrl_gamma: 0.95
ctrl_act_noise: 0.05
ctrl_consecutive_actions: 10
ctrl_max_steps: 1000
ctrl_render: False