vae_n_train_steps: 40000
vae_n_steps_per_epoch: 200
vae_batch_size: 512
vae_commitment_cost: 0.25
vae_n_embeddings: 64
vae_d_embeddings: 32
vae_frame_stack: 1
vae_weights_path: 'vae_models/'
vae_train_stats_path: 'vae_models/train_stats/'