ctrl_n_runs: 20
ctrl_n_plan_steps: 70
ctrl_n_warmup_steps: 5
ctrl_n_rollouts: 350
ctrl_n_iterations: 5
ctrl_top_perc: 0.1
ctrl_gamma: 0.9
ctrl_act_noise: 0.05
ctrl_consecutive_actions: 5
ctrl_max_steps: 50
ctrl_render: False