ctrl_n_runs: 20
ctrl_n_plan_steps: 100
ctrl_n_warmup_steps: 1
ctrl_n_rollouts: 1000
ctrl_n_iterations: 10
ctrl_top_perc: 0.2
ctrl_gamma: 0.95
ctrl_act_noise: 0.05
ctrl_consecutive_actions: 100
ctrl_max_steps: 100
ctrl_render: False