ctrl_n_runs: 30
ctrl_n_plan_steps: 60
ctrl_n_warmup_steps: 5
ctrl_n_rollouts: 500
ctrl_n_iterations: 5
ctrl_top_perc: 0.1
ctrl_gamma: 0.95
ctrl_act_noise: 0.05
ctrl_consecutive_actions: 30
ctrl_max_steps: 3000
ctrl_render: False